### ISSUE TITLE
java.nio.file.AccessDeniedException thrown on windows during creation of the DBDirectory

### ISSUE THREAD

**Issue by david-bouyssie** [yahoo/HaloDB#11]
When running the Readme example I have the following issue on a windows system:

```
Exception in thread "main" com.oath.halodb.HaloDBException: Failed to open db halodb_directory
	at com.oath.halodb.HaloDB.open(HaloDB.java:29)
	at com.oath.halodb.HaloDB.open(HaloDB.java:35)
....
Caused by: java.nio.file.AccessDeniedException: D:\halodb_directory
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:115)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at com.oath.halodb.DBDirectory.openReadOnlyChannel(DBDirectory.java:76)
	at com.oath.halodb.DBDirectory.open(DBDirectory.java:35)
	at com.oath.halodb.HaloDBInternal.open(HaloDBInternal.java:79)
	at com.oath.halodb.HaloDB.open(HaloDB.java:26)
	... 12 more
```

This is a known issue:
http://mail.openjdk.java.net/pipermail/nio-dev/2013-February/002123.html
https://issues.apache.org/jira/browse/HDFS-13586
https://github.com/permazen/permazen/issues/7
https://github.com/cryptomator/fuse-nio-adapter/issues/5

I think the fix made in this commit could be ported to HaloDB:
https://github.com/permazen/permazen/commit/287c94cf70751ab889195ef4ea80c5339354cbfe

**Comment by david-bouyssie** [comment]
I fixed this issue by slightly modifying the DBDirectory class:

```
    private static final boolean isWindows = System.getProperty("os.name", "generic").toLowerCase(java.util.Locale.ENGLISH).indexOf("win") != -1;

    void syncMetaData() {
        try {
            if (this.directoryChannel != null)
            	directoryChannel.force(true);
        } catch (IOException e) {}
    }

    private static FileChannel openReadOnlyChannel(File dbDirectory) throws IOException {
        try {
            return FileChannel.open(dbDirectory.toPath());
        } catch (IOException e) {
            if (DBDirectory.isWindows) return null;
            else throw e;
        }
    }
```

Some tests are still failing (JVM fork stuffs) but the JAR I generated while skipping tests is working on my system :D

**Comment by amannaly** [comment]
Thank you for reporting this issue. 
HaloDB has never been tested on Windows. It currently runs on Linux in production and has been tested on MacOS.  Do you want to open a pull request with your fix? You may also need to check if `directoryChannel` is null in `close()` method. 

Which are the tests that fails on Windows?

**Comment by david-bouyssie** [comment]
Sorry, but I fear I won't have the time to work on a PR.
Add I think this fix could be easily added to your master branch.

BTW, you are right, I forgot to include the change I made to the close method:
```
    void close() throws IOException {
        if (directoryChannel != null) directoryChannel.close();
    }
```

About the other windows issues, here is the list of the failing tests:

```
2018-12-06 09:11:41,458 INFO   [TestListener] Running com.oath.halodb.HaloDBFileTest.testCorruptedHeader
2018-12-06 09:11:41,493 ERROR  [HaloDBFile] Error in iterator
com.oath.halodb.HaloDBException: Corrupted header at 14915 in file 100
        at com.oath.halodb.HaloDBFile.readRecord(HaloDBFile.java:98) ~[classes/:?]
        at com.oath.halodb.HaloDBFile.access$100(HaloDBFile.java:32) ~[classes/:?]
        at com.oath.halodb.HaloDBFile$HaloDBFileIterator.next(HaloDBFile.java:357) [classes/:?]
        at com.oath.halodb.HaloDBFileTest.testCorruptedHeader(HaloDBFileTest.java:114) [test-classes/:?]
```

```
2018-12-06 09:11:42,511 INFO   [TestListener] Running com.oath.halodb.HaloDBFileTest.testFileWithInvalidRecord
2018-12-06 09:11:42,534 ERROR  [HaloDBFile] Error in iterator
com.oath.halodb.HaloDBException: Corrupted header at 14490 in file 100
        at com.oath.halodb.HaloDBFile.readRecord(HaloDBFile.java:92) ~[classes/:?]
        at com.oath.halodb.HaloDBFile.access$100(HaloDBFile.java:32) ~[classes/:?]
        at com.oath.halodb.HaloDBFile$HaloDBFileIterator.next(HaloDBFile.java:357) [classes/:?]
        at com.oath.halodb.HaloDBFileTest.testFileWithInvalidRecord(HaloDBFileTest.java:84) [test-classes/:?]
```

```
2018-12-06 09:11:46,388 INFO   [TestListener] Running com.oath.halodb.SyncWriteTest.testSyncWrites
[ERROR] Tests run: 274, Failures: 9, Errors: 0, Skipped: 118, Time elapsed: 245.849 s <<< FAILURE! - in TestSuite
[ERROR] testCopyMultipleTombstoneFiles(com.oath.halodb.TombstoneFileCleanUpTest)  Time elapsed: 0.492 s  <<< FAILURE!
java.lang.AssertionError: expected [2] but found [4]
        at com.oath.halodb.TombstoneFileCleanUpTest.testCopyMultipleTombstoneFiles(TombstoneFileCleanUpTest.java:244)

[ERROR] closeDB(com.oath.halodb.TombstoneFileCleanUpTest)  Time elapsed: 0.5 s  <<< FAILURE!
java.nio.file.FileSystemException:
tmp\TombstoneFileCleanUpTest\testCopyMultipleTombstoneFiles\1544083674.index: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.


[ERROR] closeDB(com.oath.halodb.TombstoneFileCleanUpTest)  Time elapsed: 0.006 s  <<< FAILURE!
java.nio.file.FileSystemException:
tmp\TombstoneFileCleanUpTest\testCopyMultipleTombstoneFiles\1544083674.index: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.


[ERROR] closeDB(com.oath.halodb.TombstoneFileCleanUpTest)  Time elapsed: 0.006 s  <<< FAILURE!
java.nio.file.FileSystemException:
tmp\TombstoneFileCleanUpTest\testCopyMultipleTombstoneFiles\1544083674.index: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.


[ERROR] closeDB(com.oath.halodb.TombstoneFileCleanUpTest)  Time elapsed: 0.006 s  <<< FAILURE!
java.nio.file.FileSystemException:
tmp\TombstoneFileCleanUpTest\testCopyMultipleTombstoneFiles\1544083674.index: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.


[ERROR] closeDB(com.oath.halodb.TombstoneFileCleanUpTest)  Time elapsed: 0.008 s  <<< FAILURE!
java.nio.file.FileSystemException:
tmp\TombstoneFileCleanUpTest\testCopyMultipleTombstoneFiles\1544083674.index: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.


[ERROR] testRepairFileWithCorruptedEntry(com.oath.halodb.TombstoneFileTest)  Time elapsed: 0.041 s  <<< FAILURE!
java.nio.file.FileSystemException:
tmp\TombstoneFileTest\100.tombstone.repair -> tmp\TombstoneFileTest\100.tombstone: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.

        at com.oath.halodb.TombstoneFileTest.testRepairFileWithCorruptedEntry(TombstoneFileTest.java:74)

[ERROR] after(com.oath.halodb.TombstoneFileTest)  Time elapsed: 0.041 s  <<< FAILURE!
java.nio.file.FileSystemException:
tmp\TombstoneFileTest\100.tombstone: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.

        at com.oath.halodb.TombstoneFileTest.after(TombstoneFileTest.java:54)

[ERROR] after(com.oath.halodb.HaloDBFileTest)  Time elapsed: 0.028 s  <<< FAILURE!
java.nio.file.FileSystemException:
tmp\HaloDBFileTest\testIndexFile\100.index: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.

        at com.oath.halodb.HaloDBFileTest.after(HaloDBFileTest.java:53)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR] com.oath.halodb.HaloDBFileTest.after(com.oath.halodb.HaloDBFileTest)
[ERROR]   Run 1: HaloDBFileTest.after:53 » FileSystem tmp\HaloDBFileTest\testIndexFile\100.inde...
[INFO]   Run 2: PASS
[INFO]   Run 3: PASS
[INFO]   Run 4: PASS
[INFO]   Run 5: PASS
[INFO]   Run 6: PASS
[INFO]
[ERROR] com.oath.halodb.TombstoneFileCleanUpTest.closeDB(com.oath.halodb.TombstoneFileCleanUpTest)
[ERROR]   Run 1: TombstoneFileCleanUpTest>TestBase.closeDB:68 » FileSystem tmp\TombstoneFileCle...
[ERROR]   Run 2: TombstoneFileCleanUpTest>TestBase.closeDB:68 » FileSystem tmp\TombstoneFileCle...
[ERROR]   Run 3: TombstoneFileCleanUpTest>TestBase.closeDB:68 » FileSystem tmp\TombstoneFileCle...
[ERROR]   Run 4: TombstoneFileCleanUpTest>TestBase.closeDB:68 » FileSystem tmp\TombstoneFileCle...
[ERROR]   Run 5: TombstoneFileCleanUpTest>TestBase.closeDB:68 » FileSystem tmp\TombstoneFileCle...
[INFO]
[ERROR]   TombstoneFileCleanUpTest.testCopyMultipleTombstoneFiles:244 expected [2] but found [4]
[ERROR] com.oath.halodb.TombstoneFileTest.after(com.oath.halodb.TombstoneFileTest)
[ERROR]   Run 1: TombstoneFileTest.after:54 » FileSystem tmp\TombstoneFileTest\100.tombstone: L...
[INFO]   Run 2: PASS
[INFO]   Run 3: PASS
[INFO]
[ERROR]   TombstoneFileTest.testRepairFileWithCorruptedEntry:74 » FileSystem tmp\Tombsto...
[INFO]
[ERROR] Tests run: 219, Failures: 5, Errors: 0, Skipped: 67
```

I hope its helpful.

**Comment by wangtao724** [comment]
Close as fixed

**Comment by yosraa** [comment]
To avoid this exception AcessDeniedException, I had modified the file path with the below code
        ```
        String tempFolder       = System.getProperty( "java.io.tmpdir" );
        String folderSeparator = System.getProperty( "file.separator" );
        String path                  = tempFolder + folderSeparator + "name_file";
```
